#######################################################################
# Sentinel - CONFIGURATION                                          #
#######################################################################

# ---------------------------------------------------------------------
# Application
# ---------------------------------------------------------------------
# General application configuration
app:
  mode: "dev"
  port: "8080"
  version: "1.0.0"
  name: "sentinel"
  expire: 200 # Day

# ---------------------------------------------------------------------
# JWT
# ---------------------------------------------------------------------
# JWT token for authentication
auth:
  jwt_key: |
    superlongtext
    superlongtext
    superlongtext

# ---------------------------------------------------------------------
# Database
# ---------------------------------------------------------------------
# Supported Database Engines:
# - postgres = PostgreSQL 9.5 or later
db:
  active: false
  url: "postgres://sentinel:sentinel@localhost:5432/sentinel"

# ---------------------------------------------------------------------
# Cache
# ---------------------------------------------------------------------
cache:
  active: false
  url: "redis://default:sentinel@localhost:6379/0"

# ---------------------------------------------------------------------
# Kafka Broker
# ---------------------------------------------------------------------
broker:
  url: "kafka://:@localhost:9092/file-uploaded-topic"
  consumer_group: "cg-fileuploader"
  topic: "file-uploaded-topic"

# ---------------------------------------------------------------------
# Cookies
# ---------------------------------------------------------------------
cookie:
  name: "jwt-token"
  max_age: 86400
  secure: false
  http_only: true

# ---------------------------------------------------------------------
# Session
# ---------------------------------------------------------------------
session:
  name: "session-id"
  prefix: "api-session"
  expire: 3600

# ---------------------------------------------------------------------
# Metrics (Prometheus)
# ---------------------------------------------------------------------
metrics:
  url: "0.0.0.0:7070"
  service: "api"

# ---------------------------------------------------------------------
# Tracing (Jaeger)
# ---------------------------------------------------------------------
jaeger:
  host: "localhost:6831"
  service_name: "REST_API"
  log_spans: false

# ---------------------------------------------------------------------
# Email
# ---------------------------------------------------------------------
mail:
  host: "HOST"
  port: "587"
  username: "USERNAME"
  password: "PASSWORD"
  from_name: "Sentinel"
  from_mail: "noreply@sentinel.com.tr"
  subject: "Sentinel"
  to: ""
  cc: ""
