#######################################################################
# Sentinel - CONFIGURATION                                               #
#######################################################################

app:
  env: "dev"
  version: "1.0.0"
  name: "Sentinel"
  # target application name like a Paradoks
  target: "Sentinel"
  to_users: "mail1, mail2, mail3"
  cc_users: "mail1, mail2, mail3"
  expire_day: 30

# ---------------------------------------------------------------------
# Database
# ---------------------------------------------------------------------
# Supported Database Engines:
# - postgres = PostgreSQL 9.5 or later
db:
  type: postgres

  # PostgreSQL:
  host: "HOST"
  port: 5432
  user: "USER"
  pass: "PASSWORD"
  db: "DATABASE NAME"
  ssl: "disable"

# ---------------------------------------------------------------------
# SMTP Mail Server
# ---------------------------------------------------------------------
mail:
  host: "HOST"
  port: "587"
  username: "USERNAME"
  password: "PASSWORD" # ""
  from_name: "Sentinel"
  from_mail: "noreply@sentinel.com.tr"
